# Generated by Django 5.2.8 on 2025-11-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
