# Generated by Django 5.2.8 on 2025-11-10 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения верификации'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('not_verified', 'Не верифицирован'), ('pending', 'На проверке'), ('verified', 'Верифицирован'), ('rejected', 'Отклонен')], default='not_verified', max_length=20, verbose_name='Статус верификации'),
        ),
        migrations.CreateModel(
            name='BoatOwnerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_scan', models.ImageField(upload_to='verification/passports/', verbose_name='Паспорт (скан)')),
                ('gims_documents', models.FileField(help_text='Документы на судно от ГИМС', upload_to='verification/gims/', verbose_name='Разрешительные документы ГИМС')),
                ('insurance', models.FileField(upload_to='verification/insurance/', verbose_name='Страховка')),
                ('boat_photos', models.JSONField(default=list, help_text='Список URL фотографий судна (3-5 ракурсов)', verbose_name='Фото судна')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Примечания администратора')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'boat_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Верификация владельца катера',
                'verbose_name_plural': 'Верификации владельцев катеров',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
