# Generated by Django 5.2.8 on 2025-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_verification_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boatownerverification',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Верификация владельца судна', 'verbose_name_plural': 'Верификации владельцев судов'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Клиент'), ('boat_owner', 'Владелец судна'), ('guide', 'Гид')], default='customer', max_length=20, verbose_name='Роль'),
        ),
    ]
