# Generated by Django 5.2.8 on 2025-12-06 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Примечания администратора')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.OneToOneField(limit_choices_to={'role__in': ['boat_owner', 'guide']}, on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Верификация пользователя',
                'verbose_name_plural': 'Верификации пользователей',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Документ или фотография для верификации', upload_to='verification/documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.userverification', verbose_name='Верификация')),
            ],
            options={
                'verbose_name': 'Документ верификации',
                'verbose_name_plural': 'Документы верификации',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='BoatOwnerVerification',
        ),
    ]
