# Generated by Django 5.2.8 on 2026-01-26 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Клиент'), ('boat_owner', 'Владелец судна'), ('guide', 'Гид'), ('hotel', 'Гостиница')], default='customer', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['boat_owner', 'guide', 'hotel']}, on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
