# Generated by Django 5.2.8 on 2026-01-26 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role_alter_userverification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['boat_owner', 'guide']}, on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
