# Generated by Django 5.2.8 on 2026-01-14 10:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_alter_booking_boat_alter_booking_price_per_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(help_text='PaymentId, возвращаемый API Т-Банка', max_length=100, unique=True, verbose_name='ID платежа в Т-Банке')),
                ('order_id', models.CharField(help_text='Уникальный идентификатор заказа в нашей системе', max_length=255, unique=True, verbose_name='ID заказа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма платежа (₽)')),
                ('payment_type', models.CharField(choices=[('deposit', 'Предоплата'), ('remaining', 'Остаток'), ('full', 'Полная оплата')], max_length=20, verbose_name='Тип платежа')),
                ('status', models.CharField(choices=[('new', 'Создан'), ('form_showed', 'Форма показана'), ('authorizing', 'Авторизация'), ('authorized', 'Авторизован'), ('confirming', 'Подтверждение'), ('confirmed', 'Подтвержден'), ('reversing', 'Отмена'), ('reversed', 'Отменен'), ('refunding', 'Возврат'), ('partial_refunded', 'Частичный возврат'), ('refunded', 'Возвращен'), ('rejected', 'Отклонен'), ('deadline_expired', 'Истек срок')], default='new', max_length=30, verbose_name='Статус')),
                ('payment_url', models.URLField(blank=True, help_text='URL для перенаправления пользователя на оплату', max_length=500, verbose_name='Ссылка для оплаты')),
                ('success_url', models.URLField(blank=True, max_length=500, verbose_name='URL успешной оплаты')),
                ('fail_url', models.URLField(blank=True, max_length=500, verbose_name='URL неудачной оплаты')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='Код ошибки')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('raw_response', models.JSONField(blank=True, help_text='JSON ответ от API для отладки', null=True, verbose_name='Полный ответ от Т-Банка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'payment_type'], name='payments_pa_booking_337367_idx'), models.Index(fields=['payment_id'], name='payments_pa_payment_6c9e39_idx'), models.Index(fields=['order_id'], name='payments_pa_order_i_1d1c93_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
            },
        ),
    ]
