# Generated by Django 5.2.8 on 2026-02-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_hotel_admin_booking_hotel_cashback_amount_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cache_key',
            field=models.CharField(blank=True, help_text='Ключ для получения временных данных бронирования из кэша', max_length=255, verbose_name='Ключ кэша'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Бронирование (может быть пустым для pending bookings)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='Бронирование'),
        ),
    ]
