# Generated by Django 5.2.8 on 2026-04-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_cache_key_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cache_key',
            field=models.CharField(blank=True, default='', help_text='Ключ для получения временных данных бронирования из кэша', max_length=255, verbose_name='Ключ кэша'),
        ),
    ]
