# Generated by Django 5.2.8 on 2025-12-21 10:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='URL-адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='faq/pages/', verbose_name='Изображение')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Страница FAQ',
                'verbose_name_plural': 'Страницы FAQ',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at', 'is_published'], name='faq_faqpage_publish_f886a6_idx')],
            },
        ),
    ]
