# Generated by Django 5.2.8 on 2025-11-10 12:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость (чел.)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('base_price_per_person', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Базовая ставка за человека (₽)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='boats/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Катер',
                'verbose_name_plural': 'Катера',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True, verbose_name='День недели')),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='Конкретная дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('min_duration_hours', models.PositiveIntegerField(default=1, verbose_name='Минимальная длительность (часы)')),
                ('max_duration_hours', models.PositiveIntegerField(default=8, verbose_name='Максимальная длительность (часы)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='boats.boat', verbose_name='Катер')),
            ],
            options={
                'verbose_name': 'Расписание доступности',
                'verbose_name_plural': 'Расписания доступности',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
