# Generated by Django 5.2.8 on 2025-11-10 12:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideBoatDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Процент скидки от базовой цены', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('boat_owner', models.ForeignKey(limit_choices_to={'role': 'boat_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='guide_discounts_given', to=settings.AUTH_USER_MODEL, verbose_name='Владелец катера')),
                ('guide', models.ForeignKey(limit_choices_to={'role': 'guide'}, on_delete=django.db.models.deletion.CASCADE, related_name='guide_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Гид')),
            ],
            options={
                'verbose_name': 'Скидка для гида',
                'verbose_name_plural': 'Скидки для гидов',
                'ordering': ['-created_at'],
                'unique_together': {('guide', 'boat_owner')},
            },
        ),
    ]
