# Generated by Django 5.2.8 on 2025-11-10 14:36

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_guideboatdiscount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Судно', 'verbose_name_plural': 'Судна'},
        ),
        migrations.AlterModelOptions(
            name='boatavailability',
            options={'ordering': ['departure_date', 'departure_time'], 'verbose_name': 'Расписание доступности', 'verbose_name_plural': 'Расписания доступности'},
        ),
        migrations.RemoveField(
            model_name='boat',
            name='base_price_per_person',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='image',
        ),
        migrations.RemoveField(
            model_name='boatavailability',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='boatavailability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='boatavailability',
            name='max_duration_hours',
        ),
        migrations.RemoveField(
            model_name='boatavailability',
            name='min_duration_hours',
        ),
        migrations.RemoveField(
            model_name='boatavailability',
            name='specific_date',
        ),
        migrations.RemoveField(
            model_name='boatavailability',
            name='start_time',
        ),
        migrations.AddField(
            model_name='boat',
            name='boat_type',
            field=models.CharField(choices=[('boat', 'Катер'), ('yacht', 'Яхта'), ('barkas', 'Баркас')], default='boat', max_length=20, verbose_name='Тип судна'),
        ),
        migrations.AddField(
            model_name='boatavailability',
            name='departure_date',
            field=models.DateField(default=datetime.date.today, help_text='Например: 7 ноября', verbose_name='Дата выхода'),
        ),
        migrations.AddField(
            model_name='boatavailability',
            name='departure_time',
            field=models.TimeField(default=datetime.time(12, 0), help_text='Например: 12:00', verbose_name='Время выхода'),
        ),
        migrations.AddField(
            model_name='boatavailability',
            name='return_time',
            field=models.TimeField(default=datetime.time(14, 0), help_text='Например: 14:00', verbose_name='Время возвращения'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Максимум 11 человек (12 включая капитана)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Вместимость (чел.)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание и особенности'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название судна'),
        ),
        migrations.AlterField(
            model_name='boatavailability',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='boats.boat', verbose_name='Судно'),
        ),
        migrations.AlterField(
            model_name='guideboatdiscount',
            name='boat_owner',
            field=models.ForeignKey(limit_choices_to={'role': 'boat_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='guide_discounts_given', to=settings.AUTH_USER_MODEL, verbose_name='Владелец судна'),
        ),
        migrations.CreateModel(
            name='BoatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='boats/gallery/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boats.boat', verbose_name='Судно')),
            ],
            options={
                'verbose_name': 'Фото судна',
                'verbose_name_plural': 'Фото судна',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SailingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('description', models.TextField(blank=True, verbose_name='Описание маршрута')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('boats', models.ManyToManyField(blank=True, related_name='sailing_zones', to='boats.boat', verbose_name='Судна')),
            ],
            options={
                'verbose_name': 'Зона плавания',
                'verbose_name_plural': 'Зоны плавания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoatFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('toilet', 'Туалет на судне'), ('blankets', 'Теплые пледы'), ('raincoats', 'Дождевики'), ('tea_coffee', 'Чай и кофе'), ('fishing_rods', 'Удочки для рыбалки')], max_length=30, verbose_name='Особенность')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='boats.boat', verbose_name='Судно')),
            ],
            options={
                'verbose_name': 'Особенность судна',
                'verbose_name_plural': 'Особенности судна',
                'unique_together': {('boat', 'feature_type')},
            },
        ),
        migrations.CreateModel(
            name='BoatPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_hours', models.IntegerField(choices=[(2, '2 часа'), (3, '3 часа')], verbose_name='Длительность')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость за человека (₽)')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='boats.boat', verbose_name='Судно')),
            ],
            options={
                'verbose_name': 'Стоимость прогулки',
                'verbose_name_plural': 'Стоимость прогулок',
                'unique_together': {('boat', 'duration_hours')},
            },
        ),
    ]
