# Generated by Django 5.2.8 on 2025-11-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0003_alter_boat_options_alter_boatavailability_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название особенности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='boat',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='boats', to='boats.feature', verbose_name='Особенности'),
        ),
        migrations.DeleteModel(
            name='BoatFeature',
        ),
    ]
