# Generated by Django 5.2.8 on 2025-12-01 12:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0004_change_features_to_manytomany'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата начала блокировки')),
                ('date_to', models.DateField(verbose_name='Дата окончания блокировки')),
                ('reason', models.CharField(choices=[('maintenance', 'Техобслуживание'), ('personal', 'Личные планы'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Причина блокировки')),
                ('reason_text', models.TextField(blank=True, help_text='Подробное описание причины блокировки', verbose_name='Дополнительная информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='boats.boat', verbose_name='Судно')),
            ],
            options={
                'verbose_name': 'Блокировка даты',
                'verbose_name_plural': 'Блокировки дат',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата начала действия')),
                ('date_to', models.DateField(verbose_name='Дата окончания действия')),
                ('duration_hours', models.IntegerField(choices=[(2, '2 часа'), (3, '3 часа')], verbose_name='Длительность')),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Цена за человека для указанного периода и длительности', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость за человека (₽)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_pricing', to='boats.boat', verbose_name='Судно')),
            ],
            options={
                'verbose_name': 'Сезонная цена',
                'verbose_name_plural': 'Сезонные цены',
                'ordering': ['-date_from'],
            },
        ),
    ]
