# Generated by Django 5.2.8 on 2026-01-20 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_blockeddate_seasonalpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название причала')),
                ('yandex_location_url', models.URLField(blank=True, help_text='URL ссылка на локацию причала в Яндекс.Картах', max_length=500, verbose_name='Ссылка на Яндекс.Карты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Причал',
                'verbose_name_plural': 'Причалы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='boat',
            name='dock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats', to='boats.dock', verbose_name='Причал'),
        ),
    ]
