# Generated by Django 5.2.8 on 2026-01-26 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0006_dock_boat_dock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBoatCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_percent', models.DecimalField(decimal_places=2, help_text='Процент кешбэка от стоимости бронирования', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Кешбэк (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('boat_owner', models.ForeignKey(limit_choices_to={'role': 'boat_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_cashbacks_given', to=settings.AUTH_USER_MODEL, verbose_name='Владелец судна')),
                ('hotel', models.ForeignKey(limit_choices_to={'role': 'hotel'}, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_cashbacks', to=settings.AUTH_USER_MODEL, verbose_name='Гостиница')),
            ],
            options={
                'verbose_name': 'Кешбэк для гостиницы',
                'verbose_name_plural': 'Кешбэки для гостиниц',
                'ordering': ['-created_at'],
                'unique_together': {('hotel', 'boat_owner')},
            },
        ),
    ]
