# Generated by Django 5.2.8 on 2026-03-24 10:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0008_boatavailability_capacity_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dock',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание'),
        ),
    ]
