# Generated by Django 5.2.8 on 2026-03-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0009_dock_description_richtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatavailability',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Прошедшие рейсы автоматически перемещаются в архив', verbose_name='В архиве'),
        ),
    ]
