# Generated by Django 5.2.8 on 2026-03-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0010_add_is_archived_to_boatavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatavailability',
            name='is_archived',
        ),
    ]
