# Generated by Django 5.2.8 on 2026-04-13 12:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0011_remove_is_archived_from_boatavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatavailability',
            name='trip_type',
            field=models.CharField(choices=[('group', 'Групповой'), ('individual', 'Индивидуальный (Чарт)')], default='group', help_text='Групповой — общий рейс с ценой за человека. Индивидуальный (Чарт) — аренда катера целиком с почасовой оплатой.', max_length=20, verbose_name='Тип выхода'),
        ),
        migrations.CreateModel(
            name='CharterPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_hours', models.PositiveIntegerField(help_text='Количество часов аренды', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Длительность (часы)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Полная стоимость аренды катера за указанное количество часов', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость аренды (₽)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charter_pricing', to='boats.boat', verbose_name='Судно')),
            ],
            options={
                'verbose_name': 'Стоимость чарта',
                'verbose_name_plural': 'Стоимость чарта',
                'ordering': ['duration_hours'],
                'unique_together': {('boat', 'duration_hours')},
            },
        ),
    ]
