# Generated by Django 5.2.8 on 2026-04-16 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0012_boatavailability_trip_type_charterpricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charterpricing',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1, help_text='Количество часов аренды', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Длительность (часы)'),
        ),
    ]
