# Generated by Django 5.2.8 on 2025-11-10 12:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('duration_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность (часы)')),
                ('event_type', models.CharField(help_text='Например: "Выход в море на поиски китов"', max_length=200, verbose_name='Тип мероприятия')),
                ('guest_name', models.CharField(max_length=200, verbose_name='Имя гостя')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('number_of_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество людей')),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=2, help_text='Если не указано, будет использована базовая ставка катера', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка за человека (₽)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая стоимость (₽)')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Предоплата (₽)')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток к оплате (₽)')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Безналичный расчет'), ('online', 'Онлайн оплата')], default='card', max_length=20, verbose_name='Способ оплаты остатка')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='boats.boat', verbose_name='Катер')),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'role': 'customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['boat', 'start_datetime', 'end_datetime'], name='bookings_bo_boat_id_4a128b_idx'), models.Index(fields=['boat', 'status'], name='bookings_bo_boat_id_bd2288_idx'), models.Index(fields=['customer', 'status'], name='bookings_bo_custome_0cbf77_idx')],
            },
        ),
    ]
