# Generated by Django 5.2.8 on 2025-11-10 12:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_guideboatdiscount'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма скидки (₽)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Процент скидки, примененной к бронированию', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guide',
            field=models.ForeignKey(blank=True, help_text='Гид, который привел группу', limit_choices_to={'role': 'guide'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Гид'),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Стоимость до применения скидки', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Исходная стоимость (₽)'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guide', 'status'], name='bookings_bo_guide_i_280978_idx'),
        ),
    ]
