# Generated by Django 5.2.8 on 2025-11-10 14:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0003_alter_boat_options_alter_boatavailability_options_and_more'),
        ('bookings', '0002_booking_discount_amount_booking_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='boats.boat', verbose_name='Судно'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если не указано, будет использована ставка из стоимости прогулки для данной длительности', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка за человека (₽)'),
        ),
    ]
