# Generated by Django 5.2.8 on 2026-01-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='Идентификатор события в календаре Google для синхронизации', max_length=255, null=True, verbose_name='ID события в Google Calendar'),
        ),
    ]
