# Generated by Django 5.2.8 on 2026-01-26 08:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0006_dock_boat_dock'),
        ('bookings', '0005_booking_google_calendar_event_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код промокода', max_length=50, unique=True, verbose_name='Промокод')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Фиксированная сумма скидки в рублях', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма скидки (₽)')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, чтобы активировать промокод', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='Примененный промокод для скидки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.promocode', verbose_name='Промокод'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['promo_code'], name='bookings_bo_promo_c_1204bc_idx'),
        ),
    ]
