# Generated by Django 5.2.8 on 2026-01-26 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0007_hotelboatcashback'),
        ('bookings', '0006_promocode_booking_promo_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_admin',
            field=models.ForeignKey(blank=True, help_text='Гостиница, которая привела гостя', limit_choices_to={'role': 'hotel'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Администратор гостиницы'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_cashback_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма кешбэка гостинице (₽)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_cashback_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Процент кешбэка для гостиницы', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кешбэк гостинице (%)'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hotel_admin', 'status'], name='bookings_bo_hotel_a_8fab0e_idx'),
        ),
    ]
