# Generated by Django 5.2.8 on 2026-04-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_promocode_discount_type_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_payment_reminder_sent',
            field=models.BooleanField(default=False, help_text='Флаг для предотвращения дублирования напоминания клиенту об оплате остатка за 1 час до выхода', verbose_name='Напоминание клиенту об оплате отправлено'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('group', 'Групповой'), ('individual', 'Индивидуальный (Чарт)')], default='group', help_text='Групповой или Индивидуальный (Чарт)', max_length=20, verbose_name='Тип выхода'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guide_reminder_sent',
            field=models.BooleanField(default=False, help_text='Флаг для предотвращения дублирования напоминания гиду за 1 час до выхода', verbose_name='Напоминание гиду отправлено'),
        ),
    ]
