# Generated by Django 5.2.8 on 2025-12-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Териберка', max_length=200, verbose_name='Название сайта')),
                ('company_description', models.TextField(default='Организация морских прогулок и экскурсий в Териберке', max_length=500, verbose_name='Описание компании')),
                ('phone', models.CharField(default='+7 (123) 123-12-12', max_length=20, verbose_name='Телефон')),
                ('phone_raw', models.CharField(default='+71231231212', help_text='Телефон без пробелов и скобок для использования в tel: и WhatsApp ссылках', max_length=20, verbose_name='Телефон (для ссылок)')),
                ('whatsapp_url', models.URLField(blank=True, help_text='Например: https://wa.me/71231231212', null=True, verbose_name='WhatsApp URL')),
                ('telegram_url', models.URLField(blank=True, help_text='Например: https://t.me/teriberka', null=True, verbose_name='Telegram URL')),
                ('vk_url', models.URLField(blank=True, help_text='Например: https://vk.com/teriberka', null=True, verbose_name='ВКонтакте URL')),
                ('legal_name', models.CharField(default='ИП Иванов Иван Иванович', max_length=200, verbose_name='Юридическое название')),
                ('inn', models.CharField(default='123456789012', max_length=20, verbose_name='ИНН')),
                ('address', models.TextField(default='Мурманская область, село Териберка, ул. Морская, д. 1', max_length=500, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
