# Generated by Django 5.2.8 on 2025-12-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_url',
            field=models.URLField(blank=True, help_text='Например: https://max.ru/teriberka', null=True, verbose_name='Max URL'),
        ),
    ]
