# Generated by Django 5.2.8 on 2025-12-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_max_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Email адрес для связи', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
