# Generated by Django 5.2.8 on 2025-12-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tour_operator_info',
            field=models.TextField(blank=True, help_text='Текстовая информация о туроператоре', null=True, verbose_name='Информация о туроператоре'),
        ),
    ]
