# Generated by Django 5.2.8 on 2026-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_tour_operator_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='platform_commission_percent',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Процент комиссии, взимаемый платформой с владельцев судов (от 0 до 100)', max_digits=5, verbose_name='Комиссия платформы (%)'),
        ),
    ]
